default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  host: localhost
  pool: 5
  username: koza
  password: koza
  template: template0

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  database: bookstore_production

